name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 7 * * 6' # Runs once per week on Sunday at 7:00 AM (GMT / At 8:00 AM TN time)
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-hashnode-blog:
    name: Update my repo's README with my latest medium blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          feed_list: "https://medium.com/feed/@darkpsinight"
